include: package:lint/analysis_options.yaml

linter:
  rules:
    constant_identifier_names: false

analyzer:
  errors:
    argument_type_not_assignable: info
    list_element_type_not_assignable: info
    invalid_assignment: info
    return_of_invalid_type: info
    non_bool_operand: info